language: c

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - libcunit1-dev
      - libaio-dev
      - libssl-dev

before_script:
  - wget http://fast.dpdk.org/rel/dpdk-16.07.tar.xz
  - tar xf dpdk-16.07.tar.xz
  - pushd dpdk-16.07
  - make config T=x86_64-native-linuxapp-$CC
  - sed -i s/CONFIG_RTE_EAL_IGB_UIO=y/CONFIG_RTE_EAL_IGB_UIO=n/ build/.config
  - sed -i s/CONFIG_RTE_KNI_KMOD=y/CONFIG_RTE_KNI_KMOD=n/ build/.config
  - make
  - make install DESTDIR=.
  - export DPDK_DIR=$PWD/x86_64-native-linuxapp-$CC
  - popd

script: ./unittest.sh
